services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfg
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: appdb

  frontend:
    build:
      context: ./frontend/tfg
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: "http://localhost:8000"

volumes:
  db_data:
